# Generated by Django 3.2.18 on 2023-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='map',
            new_name='sitemap',
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='xmlsitemap',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
