# Generated by Django 3.2.18 on 2023-04-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20230420_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlsitemap',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.xmlsitemap'),
        ),
    ]
