# Generated by Django 3.2.18 on 2023-04-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_xmlsitemap_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlsitemap',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_branches', to='drugs.xmlsitemap'),
        ),
    ]
