# Generated by Django 3.2.18 on 2023-04-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20230420_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='robots',
        ),
    ]
