# Generated by Django 3.2.18 on 2023-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_remove_provider_robots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='sitemap_parser_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
