# Generated by Django 3.2.18 on 2023-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20230425_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='xmlsitemap',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
