# Generated by Django 3.2.18 on 2023-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20230425_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='sitemap_parser_code',
        ),
        migrations.AddField(
            model_name='xmlsitemap',
            name='sitemap_parser_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
