# Generated by Django 3.2.18 on 2023-04-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20230425_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Ожидает классификации'), ('in_review', 'На рассмотрении'), ('excluded', 'Исключен'), ('classified', 'Классифицирован')], default='awaiting', max_length=20),
        ),
    ]
