# Generated by Django 3.2.18 on 2023-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_drug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='warning',
            field=models.TextField(blank=True),
        ),
    ]
