# Generated by Django 3.2.18 on 2023-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_auto_20230430_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='cats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
