# Generated by Django 3.2.18 on 2023-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_auto_20230501_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='cats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
